### ISSUE TITLE
Portabello's Waters

### ISSUE THREAD

**Issue by Harcronium** [UchuServer/Uchu#74] opened 2020-09-23 05:40 UTC
Yea if you go into the waters in this zone, you will get frozen.  Only way to get out is through punches or via /fly on command.

**Comment by VaiskiKP** [comment] 2020-09-23 06:02
Pretty sure this is not a bug. Its rather just that you can't die from water yet, same thing happens in AG and other maps when you jump out of bounds

**Comment by elenawinters** [comment] 2020-09-26 08:14
> Pretty sure this is not a bug. Its rather just that you can't die from water yet, same thing happens in AG and other maps when you jump out of bounds

Exactly this. This requires some physics system stuff to do.

**Comment by Jettford** [comment] 2020-10-02 10:59
Yeah no death triggers are implemented

**Comment by enteryournamehere** [comment] 2021-11-03 12:48
This was fixed in #257

**Closed by enteryournamehere** 2021-11-03 12:48 UTC
Labels: type: enhancement, issue with: missing script, affects: gameplay
